export const mockData = {
  books: [
    {
      id: 1,
      title: "Laskar Pelangi",
      author: "Andrea Hirata",
      category: "Novel",
      isbn: "978-602-03-2679-0",
      stock: 5,
      status: "available",
    },
    {
      id: 2,
      title: "Bumi Manusia",
      author: "Pramoedya A. Toer",
      category: "Novel",
      isbn: "978-979-3062-79-0",
      stock: 3,
      status: "available",
    },
    {
      id: 3,
      title: "Atomic Habits",
      author: "James Clear",
      category: "Self-Help",
      isbn: "978-602-06-3829-9",
      stock: 0,
      status: "borrowed",
    },
  ],
  members: [
    {
      id: 1,
      memberId: "M-001",
      name: "Muhammad Fauzan",
      email: "fauzan@example.com",
      joinDate: "2024-01-10",
      status: "active",
    },
    {
      id: 2,
      memberId: "M-002",
      name: "Siti Aisyah",
      email: "aisyah@example.com",
      joinDate: "2024-02-01",
      status: "inactive",
    },
  ],
  rents: [
    {
      rentId: 1,
      member: "Muhammad Fauzan",
      book: "Bumi Manusia",
      rentDate: "2024-03-01",
      returnDate: "2024-03-15",
      status: "returned",
    },
    {
      rentId: 2,
      member: "Siti Aisyah",
      book: "Atomic Habits",
      rentDate: "2024-04-10",
      returnDate: null,
      status: "overdue",
    },
    {
      rentId: 3,
      member: "Muhammad Fauzan",
      book: "Laskar Pelangi",
      rentDate: "2024-04-15",
      returnDate: null,
      status: "borrowed",
    },
  ],
}
